<?php


function ttnyc_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node']) && $form_id == 'feature_node_form') {
    unset($form['actions']['preview']);
    $form['actions']['submit']['#value'] =t('Update Feature');
  }
}

/**
* Implementation of hook_menu().
*/
function ttnyc_menu() {
  $items = array();
  // Add a menu item for the ajax callback. Change "story-list" story list to
  // the path of your Panel page.
  $items['manage-objectives/%/%node'] = array(
    'page callback' => 'egg_show_objective',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function ttnyc_show_objective($js, $node) {
  // If the nojs didn't get changed to ajax, the user has no javascript.
  // Send them to the regular node page instead.
  if ($js == 'nojs') {
    drupal_goto('node/' . $node->nid);
  }

  // Get the render array for the node.
  $build = node_view($node);
  //$build = node_view($node, $view_mode = 'editable');

  // Render the node into html.
  //$output = render($build);
  $output = views_embed_view('objective_ajax_display', 'panel_pane_1', $node->nid);
  $row = render($build);

  // Prepare an ajax command to insert the node html into our ajax wrapper.
  $commands = array();
  $commands[] = ajax_command_html('#objective-pane', $output);
  $commands[] = ajax_command_css('.objective-row', array('backgroundColor' => 'white'));
  $commands[] = ajax_command_css('.nid-'.$node->nid, array('backgroundColor' => '#f6f5f7'));


  // Render the commands into JSON and print them.
  print ajax_render($commands);
  exit;  // Exit so Drupal doesn't have a chance to build a whole page.


//  return array(
//    '#type' => 'ajax',
//    '#commands' => $commands,
//  );

}



    // Get the HTML output of the view.
    // Replace "story_list" with the name of your View.
    // Replace "panel_pane_2" with the display ID of your view (you can see the
    // ID of the display by hovering over the display name).
//    $output = views_embed_view('objective_ajax_display', 'panel_pane_1', $node->nid);

    // Replace the existing View with the new output.
//    $commands[] = ajax_command_replace('.ajax-result-pane > *', $output);

//    ctools_ajax_render($commands);
    // above command will exit().